name: 'santi '
favicon: null
layout_spectrum: 0.5127659
typography_spectrum: 0.3
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020605'
    - '#425B77'
    - '#FFFAB3'
    - '#FCA364'
    - '#F34055'
  brandStrength: 0.375
  lightness: 0.5042553
  saturation: 0.03617021
  rhythmicContrast: 0.25
purpose: []
