analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6234043
  brandStrength: 0.3991138760466129
  lightness: 0
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.007913791
typography_spectrum: 0.3
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5127659
favicon: null
name: 'santi '
